parameters:
    app.path.photographs: /uploads/images/photographs
    
vich_uploader:
    mappings:
        photographs:
            uri_prefix:         '%app.path.photographs%'
            upload_destination: '%kernel.root_dir%/../web%app.path.photographs%'

easy_admin:
    site_name: 'Portfolio'
    entities:
        Session:
            class: App\Entity\Session
            form:
                fields:
                    - 'name'
                    - 'description'
        Photograph:
            class: App\Entity\Photograph
            form:
                fields:
                    - 'name'
                    - { property: 'photoFile', type: 'vich_image' }
                    - { property: 'session', type: 'entity', type_options: { class: 'App\Entity\Session', multiple: false } }
            list:
                fields:
                    - { property: 'photo', type: 'image', base_path: '%app.path.photographs%' }
            show:
                fields:
                    - { property: 'photo', type: 'image', base_path: '%app.path.photographs%' }