easy_admin:
    site_name: 'Portfolio'
    list:
        actions:
            - { name: 'show', icon: 'search' }
            - { name: 'edit', icon: 'pencil' }
            - { name: 'delete', icon: 'times-circle' }
    entities:
        Session:
            class: App\Entity\Session
            form:
                fields:
                    - 'name'
                    - 'description'
            list:
                fields:
                    - 'name'
                    - 'description'
#                    display photos count
            show:
                fields:
                    - 'name'
                    - 'description'
        Photograph:
            class: App\Entity\Photograph
            form:
                fields:
                    - 'name'
                    - { property: 'photoFile', type: 'file', base_path: '%photographs_directory%' }
                    - { property: 'active', type: 'checkbox' }
                    - { property: 'session', type: 'entity', type_options: { class: 'App\Entity\Session', multiple: false } }   
            list:
                fields:
                    - 'name'
                    - 'photoPath'
#                    - { property: 'photoPath', type: 'image' }
                    - { property: 'active', type: 'boolean' }
                    - { property: 'session', type: 'text' }
            show:
                fields:
                    - 'name'
                    - 'updatedAt'
                    - { property: 'photoName', type: 'image', base_path: '%photographs_directory%' }
#                    - { property: 'photoPath', type: 'image' }   or this way ?
                    - { property: 'active', type: 'boolean' }
                    - { property: 'session', type: 'text' }                   